export const INITIALIZE_TASKS = 'INITIALIZE_TASKS';
export const LIST_ALL = 'LIST_ALL';
export const ADD_TASK = 'ADD_TASK';
export const CONVERT_ADD_TO_EDIT = 'CONVERT_ADD_TO_EDIT';
export const CONVERT_EDIT_TO_ADD = 'CONVERT_EDIT_TO_ADD';
export const GET_TASK_EDITING = 'GET_TASK_EDITING';
export const EDIT_TASK = 'EDIT_TASK';
export const CHANGE_STATUS = 'CHANGE_STATUS';